config/database.js
This fixes that "sequelize deprecated String based operators are now deprecated." warning that shows up everywhere.
=> Disable operatorAliases and base database config off defaults.

package.json, test/global-setup.js, test/global-teardown.js
I moved this functionality to global teardown in 1b2c910ca8f95c21498c4626857c4a25b769734f but it wasn't functioning correctly. Added it back to global setup. It might be beneficial to have a method in the future that can do this before specific tests.
=> Wipe database (truncate all models) before test.

api/index.js, api/scale-of-belief.yml, api/security/api-key-authorize.test.js, api/security/jwt-authorize.js, api/security/jwt-authorize.test.js, db/migrate/20180326102300-create-api-user.js, models/api-user.js, models/score.test.js, package-lock.json, package.json
This PR creates a JWT security handler to handle JWT that will come in (after KMA-16 transforms the CAS service tickets into JWTs). `express-jwt` handles the actual JWT validation before our security handler gets called, but there is some backup validation logic in there as well.
=> KMA-17 - Create JWT handler

models/user.js
We were seeing empty strings in user identities which were cause many unwanted identity merges.
=> No falsy values as identities.

api/controllers/login.js, api/index.js, api/scale-of-belief.yml, api/security/api-key-authorize.js, api/security/jwt-authorize.js, api/util/util.js, package-lock.json, package.json, serverless/environment.js, test/controllers/login.test.js
This PR creates a `/login` endpoint to turn service tickets from The Key into JWTs for the client to use for authentication against the rest of the API.  This will require an environment variable `THE_KEY_SERVICE_URL` to be set up in each environment.
=> KMA-16 - service ticket endpoint

api/controllers/scores.js, api/scale-of-belief.yml, test/controllers/scores.test.js
For consistency, return an empty array from `/scores` instead of a 404 when there are no results.
=> Return empty array instead of 404

models/user.js
some sso_guids don't follow UUID versions. This changes the uuid pattern matcher to accept any hex value for the uuid version.
=> Check for hex 8-4-4-4-12 uuid instead of valid uuid versions.

api/controllers/api-users.js, api/controllers/content.js, api/controllers/scores.js, api/scale-of-belief.yml, api/util/util.js, package-lock.json, test/controllers/content.test.js, test/controllers/scores.test.js
Enable pagination for the list-returning endpoints. This will need to go together with the scoring application (https://github.com/CruGlobal/scale-of-belief-web/pull/29).
=> KMA-37 pagination

models/identity-stitcher.js
Debugging database issue let to finding that the identity stitcher wasn't working properly when it didn't match by gr_master_person_id, sso_guid or device_idfa.
It was always creating a new user if those fields didn't match, resulting in a lot of duplicate users in the database which should of been merged.
This fixes the issue by correctly looking at the number of attribute matches instead of accidentally comparing arrays.
Debugging also showed DELETE queries takins a while to execute. This has been simplified to a single DELETE from users query.
=> Fix Identity Stitcher

api/controllers/placement.js, api/scale-of-belief.yml, api/security/api-key-authorize.js, api/security/api-key-authorize.test.js, models/global-registry-client.test.js, models/placement.js, models/placement.test.js, test/controllers/placement.test.js
Add placement API endpoint. Allows anyone with a valid api token to query based on one or more user fields.
Default placement to null to differentiate between someone at 0 placement and not placed.
=> Placement API endpoint

.travis.yml, api/controllers/content.js, config/sequelize.js, db/migrate/20180906080400-create-materialized-view-unscored.js, db/refresh-materialized.js, models/unscored.js, serverless.yml, test/controllers/content.test.js, test/factory.js
This seeks to fix the query timeouts when looking for unscored content by using a materialized view.  Travis build [#482](https://travis-ci.org/CruGlobal/scale-of-belief-lambda/builds/425268235?utm_source=email&utm_medium=notification) seems to have failed migrating to the test database, but I'm not sure where that database lives. 
According to [this](https://www.postgresql.org/docs/9.4/static/sql-creatematerializedview.html) materialized views are supported via a PostgreSQL extension, so maybe that extension is not on the test database that the staging environment is using? The migration worked fine in the staging database itself.
=> KMA-49 - materialized view

config/adobe-campaign.js, kinesis/campaign.js, kinesis/placement.js, models/adobe-campaign-client.js, models/adobe-campaign-client.test.js, serverless.yml, serverless/environment.js
This PR will use an SNS queue to send placement data from the placement lambda to the campaign lambda, which will then send it to Adobe Campaign Standard.
[Jira](https://jira.cru.org/browse/KMA-56)
=> KMA-56 - Send placement to ACS

db/refresh-materialized.js
Refresh has fails on every invocation.
```
Unable to import module 'db/refresh-materialized': Error
at require (internal/module.js:11:18)
```
This fixes the required path and also updates to used computed sequelize object.
=> Fixes materialized view refresh, which has been failing.

api/controllers/content.js, api/controllers/score.js, config/sequelize.js, db/migrate/20180921075100-create-recently-scored.js, db/migrate/20180921103800-add-last-refreshed-to-unscored.js, models/recently-scored.js, models/recently-scored.test.js, models/unscored.js, scheduled/refresh-materialized.js, scheduled/refresh-materialized.test.js, test/controllers/content.test.js, test/controllers/score.test.js, test/factory.js
This PR will add a new table `recently_scored` to hold data temporarily to bridge the gap between refreshes of the `unscored` materialized view. Basically, a user will score an event, then it will go into the `recently_scored` table. The query for unscored will look at the materialized view, then at the new table to ensure they don't show up in the list of unscored. 
When the materialized view is refreshed, the `recently_scored` table is truncated.
=> KMA-49 - Add a table to track recently scored

__mocks__/aws-sdk.js, api/controllers/score.js, config/aem.js, models/aem-client.js, models/aem-client.test.js, package-lock.json, package.json, serverless.yml, serverless/environment.js, sns/sync-score.js, sns/sync-score.test.js, test/controllers/score.test.js
This PR will send an SNS message upon updating scores via [scale-of-belief-web](https://github.com/CruGlobal/scale-of-belief-web). The SNS message will call a servlet set up in AEM (see https://github.com/CruGlobal/cru-aem-content-scoring/pull/4). The servlet will find the correct node given the URL (or none if it's not an AEM URL) and save the score to the JCR (specifically the `jcr:content` node of the page found).
This PR depends on 
https://github.com/CruGlobal/ecs_config/pull/339
https://github.com/CruGlobal/cru-aem-content-scoring/pull/4
User `scale-of-belief` being created inside of AEM author
=> KMA-51 - sync scores to AEM

api/controllers/placement.js, api/controllers/recommendations.js, test/controllers/placement.test.js, test/controllers/recommendations.test.js
Testing says this should fix the majority of https://rollbar.com/Cru/scale-of-belief-lambda/items/35/
At least once per day, for a few hours, the postgres query planner is deciding it's going to be quicker to do a table scan than using the indexes. This is causing the timeouts. Removing the LIMIT 1 causes the query planner to always use the indexes. Rarely will we get more than 1 user, and when we do, just take the first (It's what LIMIT 1 would of done anyway).
This also limits the columns selected to just `id`, which is the only column used.
=> Remove LIMIT 1 from User query.

scheduled/redshift.js, scheduled/refresh-materialized.js, sns/campaign.js, sns/global-registry.js, sns/sync-score.js
Some rollbar.error() calls sent an Error argument, but many did not,
which results in rollbar.js missing a stack trace in its report.
This adds the Error as a second argument in these cases.
=> Ensure stacktraces are recorded by rollbar

models/identity-stitcher.js, models/identity-stitcher.test.js, models/user.js
Updates stitcher logic to match on `mcid`
Include `appleIdfv` and `openIdfa` in `device_idfa` values.
Ignore events from `ert.test@cru.org`
=> User and stitcher update

serverless.yml
Resource arn:aws:s3::056154071827:uri-scoring cannot contain an account id.
=> Fix invalid s3 arn.

serverless.yml
Use the new terraform managed role to invoke the migrations. Jenkins instance role (used by default) doesn't have permissions anymore.
=> Use deploy role to invoke migrations

models/unscored.js
This removes a column that hasn't existed for awhile that is being queried upon
=> Fix Unscored Model
